#!/usr/bin/env bash
set -euo pipefail

if [[ ! -d tests/Unit ]] || \
   ! find tests/Unit -type f \( -name "*Test.php" -o -name "*.phpt" \) | grep -q .; then
    echo "No unit tests found. Skipping."
    exit 0
fi

php -d memory_limit=-1 \
    vendor/bin/phpunit \
    --testdox \
    --colors=always \
    --fail-on-warning \
    --display-deprecations \
    --testsuite unit