name: Reusable CI

on:
    workflow_call:
        secrets:
            PERSONAL_ACCESS_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            UID: 0
            GID: 0
            PHP_CS_FIXER_IGNORE_ENV: 1
            COMPOSER_HOME: /tmp/composer

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up Docker Compose
              run: sudo apt-get update && sudo apt-get install -y docker-compose

            - name: Inject composer auth.json with token
              run: |
                  mkdir -p docker/composer
                  echo '{
                    "github-oauth": {
                      "github.com": "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
                    }
                  }' > docker/composer/auth.json

            - name: Build and start services
              run: ./bin/build.sh

            - name: Validate composer.json
              run: ./bin/validate.sh

            - name: Install Composer dependencies
              run: ./bin/install.sh

            - name: Run PHP CS Fixer check
              run: ./bin/dev-kit-exec.sh cs-check

            - name: Run PHPStan
              run: ./bin/dev-kit-exec.sh phpstan

            - name: Run unit tests
              run: ./bin/dev-kit-exec.sh test-unit

            - name: Run integration tests
              run: ./bin/dev-kit-exec.sh test-integration

            - name: Enforce 100% test coverage
              run: ./bin/dev-kit-exec.sh test-coverage-strict
