name: Reusable CI

on:
    workflow_call:
        secrets:
            PERSONAL_ACCESS_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PHP_CS_FIXER_IGNORE_ENV: 1
            COMPOSER_HOME: /tmp/composer
            COMPOSER_CACHE_DIR: /tmp/composer/cache
            HOME: /tmp

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Detect UID and GID
              id: user
              run: |
                  echo "uid=$(id -u)" >> "$GITHUB_OUTPUT"
                  echo "gid=$(id -g)" >> "$GITHUB_OUTPUT"

            - name: Set UID and GID in env
              run: |
                  echo "UID=${{ steps.user.outputs.uid }}" >> "$GITHUB_ENV"
                  echo "GID=${{ steps.user.outputs.gid }}" >> "$GITHUB_ENV"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up Docker Compose
              run: sudo apt-get update && sudo apt-get install -y --no-install-recommends docker-compose

            - name: Configure Git to use token
              run: |
                  git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

            - name: Make init.sh executable
              run: chmod +x ./init.sh

            - name: Dev-kit init
              run: |
                  ./init.sh
                  find .dev-kit -type f -name '*.sh' -exec chmod +x {} +

            - name: Inject composer auth.json with token
              run: .dev-kit/generate-composer-auth.sh
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            - name: Build and start services
              run: .dev-kit/build.sh

            - name: Validate composer.json
              run: .dev-kit/exec.sh validate

            - name: Install Composer dependencies
              run: .dev-kit/exec.sh install

            - name: Run PHP CS Fixer check
              run: .dev-kit/exec.sh cs-check

            - name: Run PHPStan
              run: .dev-kit/exec.sh phpstan

            - name: Run unit tests
              run: .dev-kit/exec.sh test-unit

            - name: Run integration tests
              run: .dev-kit/exec.sh test-integration

            - name: Enforce 100% test coverage
              run: .dev-kit/exec.sh test-coverage-strict

            - name: ✅ Build complete
              run: echo "All checks passed ✔️"
